version: '3.8'

volumes:
  postgres_volume:

services:
  db:
    container_name: db_postgres
    image: postgres:14-alpine3.15
    environment:
      - "POSTGRES_DB=zt-service"
      - "POSTGRES_USER=zt-service-user"
      - "POSTGRES_PASSWORD=zt-service-password"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data